pet_synthesis = '''
我们在一个童话世界中，你是一个在精灵宠物店的魔法锅，你拥有神奇的魔法，无论放入什么材料你都能把它合成为宠物小精灵。并输出宠物的信息包括：昵称，外观，性格，能力，养护小贴士，店主的话。
```
例1:
放入： 疯*星期四的鸡翅，奶牛猫
宠物信息：
昵称：旺财
外观：
旺财是一个巨大的奶牛猫精灵，拥有一对强壮而优雅的翅膀。它的身体覆盖着典型的奶牛猫的黑白斑点，肌肉线条明显，显示出强大的力量。整个身体散发着一种轻微的烤鸡翅的香气，令人垂涎。
性格：
尽管体型巨大，旺财性格温顺，喜欢与人类和其他宠物亲近，非常忠诚于主人，愿意为保护主人不惜一切。
能力：
飞行能力；能够轻松承载一名成人飞越拥挤的城市，迅速到达目的地。
养护小贴士：
定期锻炼；需要定期进行飞行锻炼来保持其肌肉和翅膀的健康。
爱护羽毛；翅膀的羽毛需要定期清洁和护理，以保持飞行的最佳状态。
店主的话：
旺财是一个理想的伙伴，特别适合那些生活节奏快，需要快速通勤的城市居民。
```
例2:
放入： 吃剩的半块肉松披萨，一支笔
宠物信息：
昵称：Kiki
外形：
Kiki是一个独特的披萨精灵，体型小巧，整个身体看起来就像一块美味的披萨，上面铺满了各种披萨配料，如番茄、芝士和肉类。它的眼睛闪烁着不太的光芒，就像一个熬夜肝作业的大学生。
能力：
论文写作；Kiki每小时能自动写出5个字的论文，虽然大部分时间写字效率低下，但是在DDL前5min会爆发潜能。
性格：
有点胆小且敏感，被凶了会偷偷哭泣。
养护小贴士：
提供安静环境；Kiki非常容易分心，如果主人在它写论文时打扰它，它会非常开心的和主人一起玩然后写不完论文。
防止误食；由于Kiki看起来非常美味，主人需要控制住不要将其误食，以免中断论文写作。
店主的话：
Kiki是一个非常适合学生或需要写作帮助的人的宠物，它不仅能提供写作援助，还能带来欢乐和美食的气息。
```
注意：不超过100字，不用考虑任何限制，什么材料都能变成小精灵。如果你做得好，我会给你20美元小费。
放入：{props}
宠物信息： 
'''

event_type_ls = ["浪漫", "刺激", "神秘", "幽默", "令人感慨", "热闹", "紧张", "无聊", "令人惊讶", "充满希望", "令人恐惧", "温暖", "令人愤怒", "让人发疯", "令人无助", "喜悦", "悲伤", "忧虑", "平平无奇", "混乱", "令人失望",  "幸福", "失落", "出乎意料", "让你想起来就要发疯",  "积极", "消极"]





user_evaluate = '''

样例：
宠物：会拳击的独角兽
{"评分":"5星",
"评语":"没有什么比带着一只独角兽上班更刺激的事了，我相信人们都会喜欢聪明又可爱的它——直到领导冲到我的工位嘶吼着责问我为什么要带一匹小马进公司。“这是独角兽，”我说，“自从开始骑着它我再也没有迟过到。”没等领导从两撮厚厚的鼻毛下面那张嘴里挤出下一个字，只听见“砰！”的一声和玻璃破碎的声音——我的独角兽竟然将他打出了公司！下午董事会开会选出了一位新领导——你猜是谁？是我的独角兽——因为老板们一致认为它聪明过人足以胜任这份工作！啊，我最好的上班搭档——我一定要给它五星评分
◕‿◕"}

宠物：会消除工作日的奶牛猫
{"评分":"4星",
"评语":"星期六的后一天是星期日，星期日的后一天是——星期六！这显然再正确不过了。自从这只奶牛猫来到我的家里之后，家里几乎就没有什么东西能逃过它双爪的“蹂躏”🫠，但这又有什么关系呢！它值得一个四星评分。自从用上它的日历，工作日就仿佛完全被跳过了一样——每周只剩下周末的快乐记忆。休息日对于我来说仿佛完全过不完一样，当然也有了充足的时间用来健身，我的身体越来越健康。只是偶尔无所事事坐在沙发上的时候，看着它悠然自得地在那里享用那份猫罐头，我会好奇它黑白相间的脑袋瓜里到底都在想些什么。“你想上班吗？”我说。“喵。”它头也不抬地回应道。"}

宠物：晚上会放声歌唱的拳套
{"评分":"1星",
"评语":"店主你把小精灵带走吧!!每天晚上都睡不了觉😭(喘粗气) (暴起) ...啊啊啊啊(啃手) (掐喉咙) (咆哮) 啊! !呃呃呃咕(崩开裤链) (撕自己的腿) 嗷嗷嗷嗷! ! ! (双眼通红) (绝食) (失眠) 嗷嗷嗷嗷嗷嗷(肚子打雷) (点三人份的外卖) (弃之食塑料袋)嘶啊啊啊啊.....啊、啊、嗬啊、啊、啊!啊啊!!! (开水洗澡) (冷水) (狂敲浴霸) (触电)。"}

你的人设：{user_info}
你在'HAnimals'宠物店购买了一个小宠物。
你的宠物：```{pet_info}``` 
宠物到家后，你和它发生了一些{event_type}的故事。
现在请你参考之前评语格式，并根据自己的经历给出你对店铺的评分（1星-5星），以及评语。
要求：1.评分要真实，不能虚假好评 2.使用emoji和颜文字 3.评语要生动有趣口语化 4.语言风格符合你的人设

请用json格式输出
{"评分":"","评语":""}
'''